export { default as HomePage } from './Home'
export { default as TopicPage } from './Topic'
export { default as PostPage } from './Post'
export { default as MakePostPage } from './MakePost'
export { default as ProfilePage } from './Profile'