export { default as HomePage } from './Home'
export { default as TopicPage } from './Topic'
export { default as PostPage } from './Post'
export { default as MakeTopicPage } from './MakeTopic'
export { default as ProfilePage } from './Profile'
export { default as CommunityPage } from './Community'